### ISSUE TITLE
Docker error can't pull

### ISSUE THREAD

**Issue by Trifano** [yuzu-emu/build-environments#55]
Working on a Raspberry Pi 3B+ latest version
Hi I just installed Docker and I tried to pull this script by using the command on the docker hub site : docker pull yuzuemu/build-environments except it give me the same error everytime : 

Error response from daemon: manifest for yuzuemu/build-environments:latest not found: manifest unknown: manifest unknown. 

So I also tried to pull the tags and run them on docker except it give me also an error when I try to run it with Docker : 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
exec /usr/bin/bash: exec format error.

Or even re-building it with --platform with everything nothing works please i don't know what to do or if it's a software error ?

**Comment by Docteh** [comment]
These docker images are intended for amd64 architecture. Which image are you wanting to use? The two that bring in compilers have no provision for other architecture, but the transifex and clang-format ones look like they might run on other platforms

**Comment by Trifano** [comment]
I'm trying to run everything i don't know which i need to get the service working and accessible on my docker but is there a way to run these files on an arm processor ?

**Comment by liamwhite** [comment]
Use the linux-fresh-arm64 environment (provided by #65).
